---
version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: consultas-prm-api
    volumes:
      - ./.env:/usr/app/.env
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8001:8000"
    networks:
      - api
      - database

  api-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: consultas-prm-api-dev
    volumes:
      - ./.env:/usr/app/.env
      - ./pyproject.toml:/usr/app/pyproject.toml
      - ./app:/usr/app/app
    ports:
      - "8001:8000"
    networks:
      - api
      - database

  database:
    image: mariadb
    container_name: database
    restart: always
    healthcheck:
      test: ["CMD", "mysql" ,"--password=root", "--user=root", "--execute=SHOW DATABASES"]
      interval: 15s
      timeout: 20s
      retries: 5
      start_period: 15s
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=gobdo
      - MARIADB_USER=gobdo_user
      - MARIADB_PASSWORD=p@ssw0rd
    networks:
      - database

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - database

networks:
  api:
    driver: bridge
  database:
    driver: bridge