[tool.poetry]
name = "fastapi-tortoise"
version = "0.1.0"
description = ""
authors = ["plusiv"]
readme = "README.md"
packages = [{include = "app"}]

[tool.poetry.dependencies]
python = "^3.11"
uvicorn = {extras = ["standard"], version = "^0.22.0"}
fastapi = "^0.95.1"
tortoise-orm = {extras = ["asyncmy"], version = "^0.19.3"}
python-dotenv = "^1.0.0"
python-jose = {extras = ["cryptography"], version = "^3.3.0"}
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
python-multipart = "^0.0.6"
aiohttp = "^3.8.4"
aiodns = "^3.0.0"
email-validator = "^2.0.0.post2"


[tool.poetry.group.dev.dependencies]
tortoise-cli = "^0.1.2"
faker = "^18.9.0"
aerich = "^0.7.1"
black = "^23.3.0"
flake8 = "^6.0.0"



[tool.aerich]
tortoise_orm = "app.core.settings.TORTOISE_ORM"
location = "app/database/migrations"
src_folder = "./."

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
