---
name: Lint Code Base


on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, labeled]
    paths:
      - "**/*.py"
      - "**/*.yaml"
      - "**/*.yml"
      - "Dockerfile"
      - ".flake8"
      - "README.md"
      - ".github/workflows/*"


jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint Code Base
        uses: super-linter/super-linter/slim@v5
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_PYTHON_BLACK: true
          VALIDATE_DOCKERFILE_HADOLINT: true
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_YAML: true
          VALIDATE_MARKDOWN: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint Python Code Base with Ruff
        uses: chartboost/ruff-action@v1
        with:
          src: "./app"
